/* Generated by JTB 1.4.4 */
package gool.parser.objc.jtb.core;

import gool.parser.objc.jtb.visitor.*;

public class ClassInterface implements INode {

  public NodeToken f0;

  public ClassName f1;

  public NodeOptional f2;

  public NodeOptional f3;

  public NodeOptional f4;

  public NodeOptional f5;

  public NodeListOptional f6;

  public NodeToken f7;

  private static final long serialVersionUID = 144L;

  public ClassInterface(final NodeToken n0, final ClassName n1, final NodeOptional n2, final NodeOptional n3, final NodeOptional n4, final NodeOptional n5, final NodeListOptional n6, final NodeToken n7) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
    f6 = n6;
    f7 = n7;
  }

  public ClassInterface(final ClassName n0, final NodeOptional n1, final NodeOptional n2, final NodeOptional n3, final NodeOptional n4, final NodeListOptional n5) {
    f0 = new NodeToken("@interface");
    f1 = n0;
    f2 = n1;
    f3 = n2;
    f4 = n3;
    f5 = n4;
    f6 = n5;
    f7 = new NodeToken("@end");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }
}
