/* Generated by JTB 1.4.4 */
package gool.parser.objc.jtb.core;

import gool.parser.objc.jtb.visitor.*;

public class ClassDeclarationList implements INode {

  public NodeToken f0;

  public ClassList f1;

  public NodeToken f2;

  private static final long serialVersionUID = 144L;

  public ClassDeclarationList(final NodeToken n0, final ClassList n1, final NodeToken n2) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
  }

  public ClassDeclarationList(final ClassList n0) {
    f0 = new NodeToken("@class");
    f1 = n0;
    f2 = new NodeToken(";");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }
}
