/* Generated by JTB 1.4.4 */
package gool.parser.objc.jtb.core;

import gool.parser.objc.jtb.visitor.*;

public class EncodeExpression implements INode {

  public NodeToken f0;

  public NodeToken f1;

  public TypeNameWithUnknownType f2;

  public NodeToken f3;

  private static final long serialVersionUID = 144L;

  public EncodeExpression(final NodeToken n0, final NodeToken n1, final TypeNameWithUnknownType n2, final NodeToken n3) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
  }

  public EncodeExpression(final TypeNameWithUnknownType n0) {
    f0 = new NodeToken("@encode");
    f1 = new NodeToken("(");
    f2 = n0;
    f3 = new NodeToken(")");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }
}
