/* Generated by JTB 1.4.4 */
package gool.parser.objc.jtb.core;

import gool.parser.objc.jtb.visitor.*;

public class FunctionDefinition implements INode {

  public NodeOptional f0;

  public Declarator f1;

  public NodeOptional f2;

  public CompoundStatement f3;

  private static final long serialVersionUID = 144L;

  public FunctionDefinition(final NodeOptional n0, final Declarator n1, final NodeOptional n2, final CompoundStatement n3) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }
}
