/* Generated by JTB 1.4.4 */
package gool.parser.objc.jtb.core;

import gool.parser.objc.jtb.visitor.*;

public class InitStatement implements INode {

  public NodeOptional f0;

  public NodeOptional f1;

  public NodeToken f2;

  public NodeListOptional f3;

  public NodeChoice f4;

  private static final long serialVersionUID = 144L;

  public InitStatement(final NodeOptional n0, final NodeOptional n1, final NodeToken n2, final NodeListOptional n3, final NodeChoice n4) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }
}
