/* Generated by JTB 1.4.4 */
package gool.parser.objc.jtb.core;

import gool.parser.objc.jtb.visitor.IRetArguVisitor;

public interface INode extends java.io.Serializable {

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu);
}
