/* Generated by JTB 1.4.4 */
package gool.parser.objc.jtb.core;

import gool.parser.objc.jtb.visitor.*;

public class InstanceMethodDeclaration implements INode {

  public NodeToken f0;

  public NodeOptional f1;

  public MethodSelector f2;

  public NodeToken f3;

  private static final long serialVersionUID = 144L;

  public InstanceMethodDeclaration(final NodeToken n0, final NodeOptional n1, final MethodSelector n2, final NodeToken n3) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
  }

  public InstanceMethodDeclaration(final NodeOptional n0, final MethodSelector n1) {
    f0 = new NodeToken("-");
    f1 = n0;
    f2 = n1;
    f3 = new NodeToken(";");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }
}
