/* Generated by JTB 1.4.4 */
package gool.parser.objc.jtb.core;

import gool.parser.objc.jtb.visitor.*;

public class KeywordDeclarator implements INode {

  public NodeOptional f0;

  public NodeToken f1;

  public NodeOptional f2;

  public NodeToken f3;

  private static final long serialVersionUID = 144L;

  public KeywordDeclarator(final NodeOptional n0, final NodeToken n1, final NodeOptional n2, final NodeToken n3) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
  }

  public KeywordDeclarator(final NodeOptional n0, final NodeOptional n1, final NodeToken n2) {
    f0 = n0;
    f1 = new NodeToken(":");
    f2 = n1;
    f3 = n2;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }
}
