/* Generated by JTB 1.4.4 */
package gool.parser.objc.jtb.core;

import gool.parser.objc.jtb.visitor.*;

public class MethodType implements INode {

  public NodeToken f0;

  public NodeChoice f1;

  public NodeToken f2;

  private static final long serialVersionUID = 144L;

  public MethodType(final NodeToken n0, final NodeChoice n1, final NodeToken n2) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
  }

  public MethodType(final NodeChoice n0) {
    f0 = new NodeToken("(");
    f1 = n0;
    f2 = new NodeToken(")");
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }
}
