package DepotParser;
/* Generated By:JavaCC: Do not edit this line. ObjCParserTreeConstants.java Version 5.0 */

public interface ObjCParserTreeConstants
{
  public int JJTTRANSLATIONUNIT = 0;
  public int JJTEXTERNALDECLARATION = 1;
  public int JJTSTRIPPEDPARENS = 2;
  public int JJTFUNCTIONDEFINITION = 3;
  public int JJTDECLARATION = 4;
  public int JJTCLASSINTERFACE = 5;
  public int JJTCLASSIMPLEMENTATION = 6;
  public int JJTCATEGORYINTERFACE = 7;
  public int JJTCATEGORYIMPLEMENTATION = 8;
  public int JJTPROTOCOLDECLARATION = 9;
  public int JJTCLASSDECLARATIONLIST = 10;
  public int JJTCLASSLIST = 11;
  public int JJTPROTOCOLREFERENCELIST = 12;
  public int JJTPROTOCOLLIST = 13;
  public int JJTOBJCIDENT = 14;
  public int JJTCLASSNAME = 15;
  public int JJTSUPERCLASSNAME = 16;
  public int JJTCOLONSUPERCLASSNAME = 17;
  public int JJTCATEGORYNAME = 18;
  public int JJTPROTOCOLNAME = 19;
  public int JJTINSTANCEVARIABLES = 20;
  public int JJTINSTANCEVARIABLEDECLARATION = 21;
  public int JJTINSTANCEVARIABLEDECLARATOR = 22;
  public int JJTVISIBILITYSPECIFICATION = 23;
  public int JJTIBOUTLET = 24;
  public int JJTPROTOCOLINTERFACEDECLARATION = 25;
  public int JJTQUALIFIEDPROTOCOLINTERFACEDECLARATION = 26;
  public int JJTINTERFACEDECLARATION = 27;
  public int JJTPROPERTYDECLARATION = 28;
  public int JJTPROPERTYATTRIBUTESDECLARATION = 29;
  public int JJTPROPERTYATTRIBUTESLIST = 30;
  public int JJTPROPERTYATTRIBUTE = 31;
  public int JJTMETHODDECLARATION = 32;
  public int JJTCLASSMETHODDECLARATION = 33;
  public int JJTINSTANCEMETHODDECLARATION = 34;
  public int JJTIMPLEMENTATIONDEFINITION = 35;
  public int JJTPROPERTYIMPLEMENTATION = 36;
  public int JJTPROPERTYSYNTHESIZELIST = 37;
  public int JJTPROPERTYSYNTHESIZEITEM = 38;
  public int JJTMETHODDEFINITION = 39;
  public int JJTCLASSMETHODDEFINITION = 40;
  public int JJTINSTANCEMETHODDEFINITION = 41;
  public int JJTMETHODSELECTORNOLIST = 42;
  public int JJTMETHODSELECTOR = 43;
  public int JJTUNARYSELECTOR = 44;
  public int JJTKEYWORDSELECTOR = 45;
  public int JJTKEYWORDDECLARATOR = 46;
  public int JJTSELECTOR = 47;
  public int JJTMETHODTYPE = 48;
  public int JJTSELECTOREXPRESSION = 49;
  public int JJTSELECTORNAME = 50;
  public int JJTKEYWORDNAME = 51;
  public int JJTPROTOCOLEXPRESSION = 52;
  public int JJTENCODEEXPRESSION = 53;
  public int JJTDECLARATIONLIST = 54;
  public int JJTDECLARATIONSPECIFIERS = 55;
  public int JJTSTORAGECLASSSPECIFIER = 56;
  public int JJTTYPESPECIFIER = 57;
  public int JJTGREEDYFIXEDNUMTYPE = 58;
  public int JJTPOSSIBLECOCOATYPE = 59;
  public int JJTPOSSIBLECORETYPE = 60;
  public int JJTPOSSIBLEUNKNOWNTYPE = 61;
  public int JJTTYPESPECIFIERWITHUNKNOWNTYPE = 62;
  public int JJTTYPEQUALIFIER = 63;
  public int JJTSTRUCTORUNIONSPECIFIER = 64;
  public int JJTSTRUCTORUNION = 65;
  public int JJTSTRUCTDECLARATIONLIST = 66;
  public int JJTINITDECLARATORLIST = 67;
  public int JJTINITDECLARATOR = 68;
  public int JJTPROTOCOLQUALIFIER = 69;
  public int JJTIN = 70;
  public int JJTSTRUCTDECLARATION = 71;
  public int JJTSPECIFIERQUALIFIERWITHUNKNOWNTYPE = 72;
  public int JJTSPECIFIERQUALIFIERLIST = 73;
  public int JJTSTRUCTDECLARATORLIST = 74;
  public int JJTSTRUCTDECLARATOR = 75;
  public int JJTENUMSPECIFIER = 76;
  public int JJTENUMERATORLIST = 77;
  public int JJTENUMERATOR = 78;
  public int JJTDECLARATOR = 79;
  public int JJTBLOCK = 80;
  public int JJTDIRECTDECLARATOR = 81;
  public int JJTPOINTER = 82;
  public int JJTTYPEQUALIFIERLIST = 83;
  public int JJTPARAMETERTYPELIST = 84;
  public int JJTPARAMETERLIST = 85;
  public int JJTPARAMETERDECLARATION = 86;
  public int JJTIDENTIFIERLIST = 87;
  public int JJTINITIALIZER = 88;
  public int JJTINITIALIZERLIST = 89;
  public int JJTTYPENAME = 90;
  public int JJTTYPENAMEWITHUNKNOWNTYPE = 91;
  public int JJTABSTRACTDECLARATOR = 92;
  public int JJTDIRECTABSTRACTDECLARATOR = 93;
  public int JJTTYPEDEFNAME = 94;
  public int JJTSTATEMENT = 95;
  public int JJTLABELEDSTATEMENT = 96;
  public int JJTINITSTATEMENT = 97;
  public int JJTEXPRESSIONSTATEMENT = 98;
  public int JJTCOMPOUNDSTATEMENT = 99;
  public int JJTSTATEMENTLIST = 100;
  public int JJTSELECTIONSTATEMENT = 101;
  public int JJTNESTEDLOGICALEXPRESSION = 102;
  public int JJTLOGICALOPERATOR = 103;
  public int JJTITERATIONSTATEMENT = 104;
  public int JJTNUMBERTYPEINIT = 105;
  public int JJTJUMPSTATEMENT = 106;
  public int JJTEXPRESSION = 107;
  public int JJTASSIGNMENTEXPRESSION = 108;
  public int JJTASSIGNMENTOPERATOR = 109;
  public int JJTCONDITIONALEXPRESSION = 110;
  public int JJTCONSTANTEXPRESSION = 111;
  public int JJTLOGICALOREXPRESSION = 112;
  public int JJTLOGICALANDEXPRESSION = 113;
  public int JJTINCLUSIVEOREXPRESSION = 114;
  public int JJTEXCLUSIVEOREXPRESSION = 115;
  public int JJTANDEXPRESSION = 116;
  public int JJTEQUALITYEXPRESSION = 117;
  public int JJTRELATIONALEXPRESSION = 118;
  public int JJTSHIFTEXPRESSION = 119;
  public int JJTADDITIVEEXPRESSION = 120;
  public int JJTMULTIPLICATIVEEXPRESSION = 121;
  public int JJTCASTEXPRESSION = 122;
  public int JJTUNARYEXPRESSION = 123;
  public int JJTUNARYOPERATOR = 124;
  public int JJTPOSTFIXEXPRESSION = 125;
  public int JJTPRIMARYEXPRESSION = 126;
  public int JJTMESSAGEEXPRESSION = 127;
  public int JJTRECEIVER = 128;
  public int JJTTYPEDEFEDIDENT = 129;
  public int JJTMESSAGESELECTOR = 130;
  public int JJTKEYWORDARGUMENT = 131;
  public int JJTARGUMENTEXPRESSIONLIST = 132;
  public int JJTCONSTANT = 133;


  public String[] jjtNodeName = {
    "TranslationUnit", //0
    "ExternalDeclaration", //1
    "StrippedParens", //2
    "FunctionDefinition", //3
    "Declaration", //4
    "ClassInterface", //5
    "ClassImplementation", //6
    "CategoryInterface", //7
    "CategoryImplementation", //8
    "ProtocolDeclaration", //9
    "ClassDeclarationList", //10
    "ClassList", //11
    "ProtocolReferenceList", //12
    "ProtocolList", //13
    "ObjCIDENT", //14
    "ClassName", //15
    "SuperClassName", //16
    "ColonSuperClassName", //17
    "CategoryName", //18
    "ProtocolName", //19
    "InstanceVariables", //20
    "InstanceVariableDeclaration", //21
    "InstanceVariableDeclarator", //22
    "VisibilitySpecification", //23
    "IBOutlet", //24
    "ProtocolInterfaceDeclaration", //25
    "QualifiedProtocolInterfaceDeclaration", //26
    "InterfaceDeclaration", //27
    "PropertyDeclaration", //28
    "PropertyAttributesDeclaration", //29
    "PropertyAttributesList", //30
    "PropertyAttribute", //31
    "MethodDeclaration", //32
    "ClassMethodDeclaration", //33
    "InstanceMethodDeclaration", //34
    "ImplementationDefinition", //35
    "PropertyImplementation", //36
    "PropertySynthesizeList", //37
    "PropertySynthesizeItem", //38
    "MethodDefinition", //39
    "ClassMethodDefinition", //40
    "InstanceMethodDefinition", //41
    "MethodSelectorNoList", //42
    "MethodSelector", //43
    "UnarySelector", //44
    "KeywordSelector", //45
    "KeywordDeclarator", //46
    "Selector", //47
    "MethodType", //48
    "SelectorExpression", //49
    "SelectorName", //50
    "KeywordName", //51
    "ProtocolExpression", //52
    "EncodeExpression", //53
    "DeclarationList", //54
    "DeclarationSpecifiers", //55
    "StorageClassSpecifier", //56
    "TypeSpecifier", //57
    "GreedyFixedNumType", //58
    "PossibleCocoaType", //59
    "PossibleCoreType", //60
    "PossibleUnknownType", //61
    "TypeSpecifierWithUnknownType", //62
    "TypeQualifier", //63
    "StructOrUnionSpecifier", //64
    "StructOrUnion", //65
    "StructDeclarationList", //66
    "InitDeclaratorList", //67
    "InitDeclarator", //68
    "ProtocolQualifier", //69
    "In", //70
    "StructDeclaration", //71
    "SpecifierQualifierWithUnknownType", //72
    "SpecifierQualifierList", //73
    "StructDeclaratorList", //74
    "StructDeclarator", //75
    "EnumSpecifier", //76
    "EnumeratorList", //77
    "Enumerator", //78
    "Declarator", //79
    "Block", //80
    "DirectDeclarator", //81
    "Pointer", //82
    "TypeQualifierList", //83
    "ParameterTypeList", //84
    "ParameterList", //85
    "ParameterDeclaration", //86
    "IdentifierList", //87
    "Initializer", //88
    "InitializerList", //89
    "TypeName", //90
    "TypeNameWithUnknownType", //91
    "AbstractDeclarator", //92
    "DirectAbstractDeclarator", //93
    "TypedefName", //94
    "Statement", //95
    "LabeledStatement", //96
    "InitStatement", //97
    "ExpressionStatement", //98
    "CompoundStatement", //99
    "StatementList", //100
    "SelectionStatement", //101
    "NestedLogicalExpression", //102
    "LogicalOperator", //103
    "IterationStatement", //104
    "NumberTypeInit", //105
    "JumpStatement", //106
    "Expression", //107
    "AssignmentExpression", //108
    "AssignmentOperator", //109
    "ConditionalExpression", //110
    "ConstantExpression", //111
    "LogicalORExpression", //112
    "LogicalANDExpression", //113
    "InclusiveORExpression", //114
    "ExclusiveORExpression", //115
    "ANDExpression", //116
    "EqualityExpression", //117
    "RelationalExpression", //118
    "ShiftExpression", //119
    "AdditiveExpression", //120
    "MultiplicativeExpression", //121
    "CastExpression", //122
    "UnaryExpression", //123
    "UnaryOperator", //124
    "PostfixExpression", //125
    "PrimaryExpression", //126
    "MessageExpression", //127
    "Receiver", //128
    "TypeDefedIDENT", //129
    "MessageSelector", //130
    "KeywordArgument", //131
    "ArgumentExpressionList", //132
    "Constant", //133
  };
}
/* JavaCC - OriginalChecksum=56f7c44b05c0bf3eb2cf02ffe32d21fd (do not edit this line) */
