/*
 * Copyright 2010 Pablo Arrighi, Alex Concha, Miguel Lezama for version 1.
 * Copyright 2013 Pablo Arrighi, Miguel Lezama, Kevin Mazet for version 2.    
 *
 * This file is part of GOOL.
 *
 * GOOL is free software: you can redistribute it and/or modify it under the terms of the GNU
 * General Public License as published by the Free Software Foundation, version 3.
 *
 * GOOL is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License version 3 for more details.
 *
 * You should have received a copy of the GNU General Public License along with GOOL,
 * in the file COPYING.txt.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * This is a Visitor. It visits the Java abstract syntax tree generated by Sun's java parser, to produce a GOOL abstract syntax tree.
 * 
 */

package gool.recognizer.objC;

import DepotParser.Node;

/**
 * The ObjCRecognizer does the work of converting javacc's abstract ObjC to
 * abstract GOOL.
 */	
//Un visiteur implémente des méthodes visit lors du parcours
//des noeux construits par le parseur. Elles sont spécifiées
//dans la classe abstraite Visitor.

//Le recognizer implémente les méthodes abstraites du visiteur.
class ObjCRecognizer extends Visitor{
	//switch
	
	void visit(Node n) {
	}

}