/* Generated by JTB 1.4.4 */
package gool.parser.objc.jtb.visitor;

import gool.parser.objc.jtb.core.*;

import java.util.*;

public class DepthFirstRetVisitor<R> implements IRetVisitor<R> {


  public R visit(final NodeChoice n) {
    final R nRes = n.choice.accept(this);
    return nRes;
  }

  public R visit(final NodeList n) {
    R nRes = null;
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      @SuppressWarnings("unused")
      final R sRes = e.next().accept(this);
    }
    return nRes;
  }

  public R visit(final NodeListOptional n) {
    if (n.present()) {
      R nRes = null;
      for (final Iterator<INode> e = n.elements(); e.hasNext();) {
        @SuppressWarnings("unused")
        R sRes = e.next().accept(this);
        }
      return nRes;
    } else
      return null;
  }

  public R visit(final NodeOptional n) {
    if (n.present()) {
      final R nRes = n.node.accept(this);
      return nRes;
    } else
    return null;
  }

  public R visit(final NodeSequence n) {
    R nRes = null;
    for (final Iterator<INode> e = n.elements(); e.hasNext();) {
      @SuppressWarnings("unused")
      R subRet = e.next().accept(this);
    }
    return nRes;
  }

  public R visit(final NodeToken n) {
    R nRes = null;
    @SuppressWarnings("unused")
    final String tkIm = n.tokenImage;
    return nRes;
  }

  public R visit(final TranslationUnit n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final ExternalDeclaration n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final StrippedParens n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    return nRes;
  }

  public R visit(final FunctionDefinition n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    return nRes;
  }

  public R visit(final Declaration n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    return nRes;
  }

  public R visit(final ClassInterface n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    n.f6.accept(this);
    n.f7.accept(this);
    return nRes;
  }

  public R visit(final ClassImplementation n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    return nRes;
  }

  public R visit(final CategoryInterface n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    n.f6.accept(this);
    n.f7.accept(this);
    return nRes;
  }

  public R visit(final CategoryImplementation n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    n.f6.accept(this);
    return nRes;
  }

  public R visit(final ProtocolDeclaration n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    return nRes;
  }

  public R visit(final ClassDeclarationList n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    return nRes;
  }

  public R visit(final ClassList n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final ProtocolReferenceList n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    return nRes;
  }

  public R visit(final ProtocolList n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final ObjCIDENT n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final ClassName n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final SuperClassName n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final ColonSuperClassName n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final CategoryName n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final ProtocolName n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final InstanceVariables n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    return nRes;
  }

  public R visit(final InstanceVariableDeclaration n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final InstanceVariableDeclarator n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final VisibilitySpecification n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final IBOutlet n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final ProtocolInterfaceDeclaration n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final QualifiedProtocolInterfaceDeclaration n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final InterfaceDeclaration n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final PropertyDeclaration n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    return nRes;
  }

  public R visit(final PropertyAttributesDeclaration n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    return nRes;
  }

  public R visit(final PropertyAttributesList n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final PropertyAttribute n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final MethodDeclaration n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final ClassMethodDeclaration n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    return nRes;
  }

  public R visit(final InstanceMethodDeclaration n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    return nRes;
  }

  public R visit(final ImplementationDefinition n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final PropertyImplementation n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final PropertySynthesizeList n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final PropertySynthesizeItem n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final MethodDefinition n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final ClassMethodDefinition n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    return nRes;
  }

  public R visit(final InstanceMethodDefinition n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    return nRes;
  }

  public R visit(final MethodSelectorNoList n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final MethodSelector n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final UnarySelector n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final KeywordSelector n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final KeywordDeclarator n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    return nRes;
  }

  public R visit(final Selector n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final MethodType n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    return nRes;
  }

  public R visit(final SelectorExpression n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    return nRes;
  }

  public R visit(final SelectorName n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final KeywordName n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final ProtocolExpression n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    return nRes;
  }

  public R visit(final EncodeExpression n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    return nRes;
  }

  public R visit(final DeclarationList n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final DeclarationSpecifiers n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final StorageClassSpecifier n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final TypeSpecifier n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final GreedyFixedNumType n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final PossibleCocoaType n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final PossibleCoreType n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final PossibleUnknownType n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final TypeSpecifierWithUnknownType n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final TypeQualifier n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final StructOrUnionSpecifier n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final StructOrUnion n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final StructDeclarationList n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final InitDeclaratorList n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final InitDeclarator n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final ProtocolQualifier n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final In n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final StructDeclaration n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    return nRes;
  }

  public R visit(final SpecifierQualifierWithUnknownType n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final SpecifierQualifierList n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final StructDeclaratorList n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final StructDeclarator n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final EnumSpecifier n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final EnumeratorList n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final Enumerator n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final Declarator n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final Block n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    n.f5.accept(this);
    n.f6.accept(this);
    return nRes;
  }

  public R visit(final DirectDeclarator n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final Pointer n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    return nRes;
  }

  public R visit(final TypeQualifierList n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final ParameterTypeList n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final ParameterList n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final ParameterDeclaration n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final IdentifierList n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final Initializer n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final InitializerList n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final TypeName n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final TypeNameWithUnknownType n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final AbstractDeclarator n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final DirectAbstractDeclarator n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final TypedefName n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final Statement n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final LabeledStatement n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final InitStatement n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    return nRes;
  }

  public R visit(final ExpressionStatement n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final CompoundStatement n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    return nRes;
  }

  public R visit(final StatementList n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final SelectionStatement n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final NestedLogicalExpression n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    n.f4.accept(this);
    return nRes;
  }

  public R visit(final LogicalOperator n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final IterationStatement n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final NumberTypeInit n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final JumpStatement n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final Expression n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final AssignmentExpression n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final AssignmentOperator n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final ConditionalExpression n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final ConstantExpression n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final LogicalORExpression n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final LogicalANDExpression n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final InclusiveORExpression n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final ExclusiveORExpression n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final ANDExpression n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final EqualityExpression n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final RelationalExpression n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final ShiftExpression n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final AdditiveExpression n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final MultiplicativeExpression n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final CastExpression n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final UnaryExpression n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final UnaryOperator n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final PostfixExpression n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final PrimaryExpression n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final MessageExpression n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    n.f2.accept(this);
    n.f3.accept(this);
    return nRes;
  }

  public R visit(final Receiver n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final TypeDefedIDENT n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final MessageSelector n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final KeywordArgument n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

  public R visit(final ArgumentExpressionList n) {
    R nRes = null;
    n.f0.accept(this);
    n.f1.accept(this);
    return nRes;
  }

  public R visit(final Constant n) {
    R nRes = null;
    n.f0.accept(this);
    return nRes;
  }

}
