/* Generated by JTB 1.4.4 */
package gool.parser.objc.jtb.visitor;

import gool.parser.objc.jtb.core.*;

public interface IRetVisitor<R> {

  public R visit(final NodeList n);

  public R visit(final NodeListOptional n);

  public R visit(final NodeOptional n);

  public R visit(final NodeSequence n);

  public R visit(final NodeToken n);

  public R visit(final TranslationUnit n);

  public R visit(final ExternalDeclaration n);

  public R visit(final StrippedParens n);

  public R visit(final FunctionDefinition n);

  public R visit(final Declaration n);

  public R visit(final ClassInterface n);

  public R visit(final ClassImplementation n);

  public R visit(final CategoryInterface n);

  public R visit(final CategoryImplementation n);

  public R visit(final ProtocolDeclaration n);

  public R visit(final ClassDeclarationList n);

  public R visit(final ClassList n);

  public R visit(final ProtocolReferenceList n);

  public R visit(final ProtocolList n);

  public R visit(final ObjCIDENT n);

  public R visit(final ClassName n);

  public R visit(final SuperClassName n);

  public R visit(final ColonSuperClassName n);

  public R visit(final CategoryName n);

  public R visit(final ProtocolName n);

  public R visit(final InstanceVariables n);

  public R visit(final InstanceVariableDeclaration n);

  public R visit(final InstanceVariableDeclarator n);

  public R visit(final VisibilitySpecification n);

  public R visit(final IBOutlet n);

  public R visit(final ProtocolInterfaceDeclaration n);

  public R visit(final QualifiedProtocolInterfaceDeclaration n);

  public R visit(final InterfaceDeclaration n);

  public R visit(final PropertyDeclaration n);

  public R visit(final PropertyAttributesDeclaration n);

  public R visit(final PropertyAttributesList n);

  public R visit(final PropertyAttribute n);

  public R visit(final MethodDeclaration n);

  public R visit(final ClassMethodDeclaration n);

  public R visit(final InstanceMethodDeclaration n);

  public R visit(final ImplementationDefinition n);

  public R visit(final PropertyImplementation n);

  public R visit(final PropertySynthesizeList n);

  public R visit(final PropertySynthesizeItem n);

  public R visit(final MethodDefinition n);

  public R visit(final ClassMethodDefinition n);

  public R visit(final InstanceMethodDefinition n);

  public R visit(final MethodSelectorNoList n);

  public R visit(final MethodSelector n);

  public R visit(final UnarySelector n);

  public R visit(final KeywordSelector n);

  public R visit(final KeywordDeclarator n);

  public R visit(final Selector n);

  public R visit(final MethodType n);

  public R visit(final SelectorExpression n);

  public R visit(final SelectorName n);

  public R visit(final KeywordName n);

  public R visit(final ProtocolExpression n);

  public R visit(final EncodeExpression n);

  public R visit(final DeclarationList n);

  public R visit(final DeclarationSpecifiers n);

  public R visit(final StorageClassSpecifier n);

  public R visit(final TypeSpecifier n);

  public R visit(final GreedyFixedNumType n);

  public R visit(final PossibleCocoaType n);

  public R visit(final PossibleCoreType n);

  public R visit(final PossibleUnknownType n);

  public R visit(final TypeSpecifierWithUnknownType n);

  public R visit(final TypeQualifier n);

  public R visit(final StructOrUnionSpecifier n);

  public R visit(final StructOrUnion n);

  public R visit(final StructDeclarationList n);

  public R visit(final InitDeclaratorList n);

  public R visit(final InitDeclarator n);

  public R visit(final ProtocolQualifier n);

  public R visit(final In n);

  public R visit(final StructDeclaration n);

  public R visit(final SpecifierQualifierWithUnknownType n);

  public R visit(final SpecifierQualifierList n);

  public R visit(final StructDeclaratorList n);

  public R visit(final StructDeclarator n);

  public R visit(final EnumSpecifier n);

  public R visit(final EnumeratorList n);

  public R visit(final Enumerator n);

  public R visit(final Declarator n);

  public R visit(final Block n);

  public R visit(final DirectDeclarator n);

  public R visit(final Pointer n);

  public R visit(final TypeQualifierList n);

  public R visit(final ParameterTypeList n);

  public R visit(final ParameterList n);

  public R visit(final ParameterDeclaration n);

  public R visit(final IdentifierList n);

  public R visit(final Initializer n);

  public R visit(final InitializerList n);

  public R visit(final TypeName n);

  public R visit(final TypeNameWithUnknownType n);

  public R visit(final AbstractDeclarator n);

  public R visit(final DirectAbstractDeclarator n);

  public R visit(final TypedefName n);

  public R visit(final Statement n);

  public R visit(final LabeledStatement n);

  public R visit(final InitStatement n);

  public R visit(final ExpressionStatement n);

  public R visit(final CompoundStatement n);

  public R visit(final StatementList n);

  public R visit(final SelectionStatement n);

  public R visit(final NestedLogicalExpression n);

  public R visit(final LogicalOperator n);

  public R visit(final IterationStatement n);

  public R visit(final NumberTypeInit n);

  public R visit(final JumpStatement n);

  public R visit(final Expression n);

  public R visit(final AssignmentExpression n);

  public R visit(final AssignmentOperator n);

  public R visit(final ConditionalExpression n);

  public R visit(final ConstantExpression n);

  public R visit(final LogicalORExpression n);

  public R visit(final LogicalANDExpression n);

  public R visit(final InclusiveORExpression n);

  public R visit(final ExclusiveORExpression n);

  public R visit(final ANDExpression n);

  public R visit(final EqualityExpression n);

  public R visit(final RelationalExpression n);

  public R visit(final ShiftExpression n);

  public R visit(final AdditiveExpression n);

  public R visit(final MultiplicativeExpression n);

  public R visit(final CastExpression n);

  public R visit(final UnaryExpression n);

  public R visit(final UnaryOperator n);

  public R visit(final PostfixExpression n);

  public R visit(final PrimaryExpression n);

  public R visit(final MessageExpression n);

  public R visit(final Receiver n);

  public R visit(final TypeDefedIDENT n);

  public R visit(final MessageSelector n);

  public R visit(final KeywordArgument n);

  public R visit(final ArgumentExpressionList n);

  public R visit(final Constant n);

}
