/* Generated by JTB 1.4.4 */
package gool.parser.objc.jtb.visitor;

import gool.parser.objc.jtb.core.*;

public interface IVoidVisitor {

  public void visit(final NodeList n);

  public void visit(final NodeListOptional n);

  public void visit(final NodeOptional n);

  public void visit(final NodeSequence n);

  public void visit(final NodeToken n);

  public void visit(final TranslationUnit n);

  public void visit(final ExternalDeclaration n);

  public void visit(final StrippedParens n);

  public void visit(final FunctionDefinition n);

  public void visit(final Declaration n);

  public void visit(final ClassInterface n);

  public void visit(final ClassImplementation n);

  public void visit(final CategoryInterface n);

  public void visit(final CategoryImplementation n);

  public void visit(final ProtocolDeclaration n);

  public void visit(final ClassDeclarationList n);

  public void visit(final ClassList n);

  public void visit(final ProtocolReferenceList n);

  public void visit(final ProtocolList n);

  public void visit(final ObjCIDENT n);

  public void visit(final ClassName n);

  public void visit(final SuperClassName n);

  public void visit(final ColonSuperClassName n);

  public void visit(final CategoryName n);

  public void visit(final ProtocolName n);

  public void visit(final InstanceVariables n);

  public void visit(final InstanceVariableDeclaration n);

  public void visit(final InstanceVariableDeclarator n);

  public void visit(final VisibilitySpecification n);

  public void visit(final IBOutlet n);

  public void visit(final ProtocolInterfaceDeclaration n);

  public void visit(final QualifiedProtocolInterfaceDeclaration n);

  public void visit(final InterfaceDeclaration n);

  public void visit(final PropertyDeclaration n);

  public void visit(final PropertyAttributesDeclaration n);

  public void visit(final PropertyAttributesList n);

  public void visit(final PropertyAttribute n);

  public void visit(final MethodDeclaration n);

  public void visit(final ClassMethodDeclaration n);

  public void visit(final InstanceMethodDeclaration n);

  public void visit(final ImplementationDefinition n);

  public void visit(final PropertyImplementation n);

  public void visit(final PropertySynthesizeList n);

  public void visit(final PropertySynthesizeItem n);

  public void visit(final MethodDefinition n);

  public void visit(final ClassMethodDefinition n);

  public void visit(final InstanceMethodDefinition n);

  public void visit(final MethodSelectorNoList n);

  public void visit(final MethodSelector n);

  public void visit(final UnarySelector n);

  public void visit(final KeywordSelector n);

  public void visit(final KeywordDeclarator n);

  public void visit(final Selector n);

  public void visit(final MethodType n);

  public void visit(final SelectorExpression n);

  public void visit(final SelectorName n);

  public void visit(final KeywordName n);

  public void visit(final ProtocolExpression n);

  public void visit(final EncodeExpression n);

  public void visit(final DeclarationList n);

  public void visit(final DeclarationSpecifiers n);

  public void visit(final StorageClassSpecifier n);

  public void visit(final TypeSpecifier n);

  public void visit(final GreedyFixedNumType n);

  public void visit(final PossibleCocoaType n);

  public void visit(final PossibleCoreType n);

  public void visit(final PossibleUnknownType n);

  public void visit(final TypeSpecifierWithUnknownType n);

  public void visit(final TypeQualifier n);

  public void visit(final StructOrUnionSpecifier n);

  public void visit(final StructOrUnion n);

  public void visit(final StructDeclarationList n);

  public void visit(final InitDeclaratorList n);

  public void visit(final InitDeclarator n);

  public void visit(final ProtocolQualifier n);

  public void visit(final In n);

  public void visit(final StructDeclaration n);

  public void visit(final SpecifierQualifierWithUnknownType n);

  public void visit(final SpecifierQualifierList n);

  public void visit(final StructDeclaratorList n);

  public void visit(final StructDeclarator n);

  public void visit(final EnumSpecifier n);

  public void visit(final EnumeratorList n);

  public void visit(final Enumerator n);

  public void visit(final Declarator n);

  public void visit(final Block n);

  public void visit(final DirectDeclarator n);

  public void visit(final Pointer n);

  public void visit(final TypeQualifierList n);

  public void visit(final ParameterTypeList n);

  public void visit(final ParameterList n);

  public void visit(final ParameterDeclaration n);

  public void visit(final IdentifierList n);

  public void visit(final Initializer n);

  public void visit(final InitializerList n);

  public void visit(final TypeName n);

  public void visit(final TypeNameWithUnknownType n);

  public void visit(final AbstractDeclarator n);

  public void visit(final DirectAbstractDeclarator n);

  public void visit(final TypedefName n);

  public void visit(final Statement n);

  public void visit(final LabeledStatement n);

  public void visit(final InitStatement n);

  public void visit(final ExpressionStatement n);

  public void visit(final CompoundStatement n);

  public void visit(final StatementList n);

  public void visit(final SelectionStatement n);

  public void visit(final NestedLogicalExpression n);

  public void visit(final LogicalOperator n);

  public void visit(final IterationStatement n);

  public void visit(final NumberTypeInit n);

  public void visit(final JumpStatement n);

  public void visit(final Expression n);

  public void visit(final AssignmentExpression n);

  public void visit(final AssignmentOperator n);

  public void visit(final ConditionalExpression n);

  public void visit(final ConstantExpression n);

  public void visit(final LogicalORExpression n);

  public void visit(final LogicalANDExpression n);

  public void visit(final InclusiveORExpression n);

  public void visit(final ExclusiveORExpression n);

  public void visit(final ANDExpression n);

  public void visit(final EqualityExpression n);

  public void visit(final RelationalExpression n);

  public void visit(final ShiftExpression n);

  public void visit(final AdditiveExpression n);

  public void visit(final MultiplicativeExpression n);

  public void visit(final CastExpression n);

  public void visit(final UnaryExpression n);

  public void visit(final UnaryOperator n);

  public void visit(final PostfixExpression n);

  public void visit(final PrimaryExpression n);

  public void visit(final MessageExpression n);

  public void visit(final Receiver n);

  public void visit(final TypeDefedIDENT n);

  public void visit(final MessageSelector n);

  public void visit(final KeywordArgument n);

  public void visit(final ArgumentExpressionList n);

  public void visit(final Constant n);

}
