/* Generated by JTB 1.4.4 */
package gool.parser.objc.jtb.core;

import gool.parser.objc.jtb.visitor.*;

public class InstanceMethodDefinition implements INode {

  public NodeToken f0;

  public NodeOptional f1;

  public MethodSelectorNoList f2;

  public NodeListOptional f3;

  public NodeOptional f4;

  public CompoundStatement f5;

  private static final long serialVersionUID = 144L;

  public InstanceMethodDefinition(final NodeToken n0, final NodeOptional n1, final MethodSelectorNoList n2, final NodeListOptional n3, final NodeOptional n4, final CompoundStatement n5) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
    f5 = n5;
  }

  public InstanceMethodDefinition(final NodeOptional n0, final MethodSelectorNoList n1, final NodeListOptional n2, final NodeOptional n3, final CompoundStatement n4) {
    f0 = new NodeToken("-");
    f1 = n0;
    f2 = n1;
    f3 = n2;
    f4 = n3;
    f5 = n4;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
