/* Generated by JTB 1.4.4 */
package gool.parser.objc.jtb.core;

import gool.parser.objc.jtb.visitor.*;

public class ProtocolReferenceList implements INode {

  public NodeToken f0;

  public ProtocolList f1;

  public NodeToken f2;

  public NodeOptional f3;

  private static final long serialVersionUID = 144L;

  public ProtocolReferenceList(final NodeToken n0, final ProtocolList n1, final NodeToken n2, final NodeOptional n3) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
  }

  public ProtocolReferenceList(final ProtocolList n0, final NodeOptional n1) {
    f0 = new NodeToken("<");
    f1 = n0;
    f2 = new NodeToken(">");
    f3 = n1;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
